FROM node:18-alpine
WORKDIR /usr/src/app

# Install build tools for native packages if needed
RUN apk add --no-cache python3 make g++ docker-cli

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5000

CMD ["node", "server.js"]
